### ISSUE TITLE
Suggestions/Review/Feedback

### ISSUE THREAD

**Issue by spykelionel** [Uthmanduro/Job-api#1]
**Review/Feedback on the JOBs API:**

1. **User Creation**: Unable to create a user. Client errors are not properly managed; for example, an invalid role triggers a 500 server error instead of a 400 Bad Request, indicating improper client input handling.

2. **API Documentation**: The API documentation lacks clarity. For instance, in the "create user" endpoint, the role field is shown as `{}`, an empty object. It would be helpful to assign a default role (e.g., "User") when none is provided, to simplify client usage.

3. **File Upload on Swagger**: The Swagger interface does not support file uploads, which prevents actions like updating a user profile picture. This feature is essential to enable clients to test file upload functionality directly in Swagger.

4. **Job Access Permissions**: All jobs should be accessible without requiring login. Currently, this isn’t the case, as accessing jobs triggers a 403 error even when logged in. This behavior should be reviewed for consistency with expected access permissions.

5. **Application Endpoint**: Users are unable to apply for jobs, which limits the ability to retrieve applications. This endpoint should be tested to ensure users can successfully apply and view applications.

6. **Error Messages and Client Payload Handling**: Error messages need to be more descriptive for the client. Additionally, client payloads should be properly validated to prevent unexpected errors.

7. **Request Logging**: There's no request logging, making error tracing challenging. Implementing request logging would greatly aid in troubleshooting and tracking client requests.

8. **Code Structure**: The API code structure is well-organized, though minor configuration adjustments are recommended. Avoiding duplicate code wherever possible would also improve maintainability.

9. **Naming Conventions**: Enum values should be in uppercase to clearly indicate them as CONSTANTS. This enhances readability and aligns with standard naming conventions.

Please review the screenshots below for further clarification.

# Screenshots
1. JOB ![image](https://github.com/user-attachments/assets/b1c54e40-066b-438a-bb1f-f2e114616cf0)
2. Create User with invalid role: 
![image](https://github.com/user-attachments/assets/d34cfccd-90b9-4532-aa53-ee9bb9d37b3d)
3.

**Comment by Uthmanduro** [comment]
Issues have been fixed and uploaded for deployment
